// <auto-generated />
using System;
using FinalProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Infrastructure.Migrations
{
    [DbContext(typeof(LukitasDbContext))]
    [Migration("20251202161724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Infrastructure.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("account_number");

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("balance")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccountNumber" }, "account_number")
                        .IsUnique();

                    b.HasIndex(new[] { "CampaignId" }, "idx_accounts_campaign");

                    b.HasIndex(new[] { "UserId" }, "idx_accounts_user");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AchievementDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("achievement_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int?>("UserMissionId")
                        .HasColumnType("int")
                        .HasColumnName("user_mission_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserMissionId" }, "fk_achievements_user_missions");

                    b.ToTable("achievements", null, t =>
                        {
                            t.HasComment("Achievements obtained by completing missions");
                        });
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<decimal?>("Budget")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("budget");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("contact_number");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Schedule")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("schedule");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StartDate", "EndDate" }, "idx_campaigns_dates");

                    b.HasIndex(new[] { "UserId" }, "idx_campaigns_user");

                    b.ToTable("campaigns", null, t =>
                        {
                            t.HasComment("Campaigns promoted by coordinators");
                        });
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("DiscountType")
                        .HasColumnType("enum('percentage','fixed_amount')")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("discount_value");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique();

                    b.HasIndex(new[] { "CampaignId" }, "fk_coupons_campaigns");

                    b.HasIndex(new[] { "SupplierId" }, "fk_coupons_suppliers");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("FinalProject.Infrastructure.MissionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int?>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reward_points")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("mission_templates", null, t =>
                        {
                            t.HasComment("Master catalog of system missions");
                        });
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'");

                    b.Property<int?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stock")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique()
                        .HasDatabaseName("code1");

                    b.HasIndex(new[] { "SupplierId" }, "idx_products_supplier");

                    b.HasIndex(new[] { "ProductTypeId" }, "idx_products_type");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("FinalProject.Infrastructure.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("product_types", (string)null);
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Permissions")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("permissions");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("roles", null, t =>
                        {
                            t.HasComment("System roles: student and coordinator");
                        });
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("SaleDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("sale_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<decimal>("Total")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccountId" }, "idx_sales_account");

                    b.HasIndex(new[] { "SaleDate" }, "idx_sales_date");

                    b.ToTable("sales", null, t =>
                        {
                            t.HasComment("sale_id serves as voucher code");
                        });
                });

            modelBuilder.Entity("FinalProject.Infrastructure.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductId" }, "fk_sale_details_products");

                    b.HasIndex(new[] { "SaleId" }, "fk_sale_details_sales");

                    b.ToTable("sale_details", (string)null);
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'");

                    b.Property<int?>("SupplierTypeId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_type_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SupplierTypeId" }, "fk_suppliers_types");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("FinalProject.Infrastructure.SupplierType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("supplier_types", (string)null);
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("DestinationAccountId")
                        .HasColumnType("int")
                        .HasColumnName("destination_account_id");

                    b.Property<int?>("SourceAccountId")
                        .HasColumnType("int")
                        .HasColumnName("source_account_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<DateOnly>("TransferDate")
                        .HasColumnType("date")
                        .HasColumnName("transfer_date");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DestinationAccountId" }, "fk_transfers_destination");

                    b.HasIndex(new[] { "SourceAccountId" }, "fk_transfers_source");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("FinalProject.Infrastructure.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("company");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("student_code");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("university");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "idx_users_role");

                    b.HasIndex(new[] { "StudentCode" }, "idx_users_student_code")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Educational system users");
                        });
                });

            modelBuilder.Entity("FinalProject.Infrastructure.UserMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AssignmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("assignment_date")
                        .HasDefaultValueSql("curdate()");

                    b.Property<bool?>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("completed")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("completion_date");

                    b.Property<int?>("MissionId")
                        .HasColumnType("int")
                        .HasColumnName("mission_id");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SaleId" }, "fk_user_missions_sales");

                    b.HasIndex(new[] { "Completed" }, "idx_user_missions_completed");

                    b.HasIndex(new[] { "MissionId" }, "idx_user_missions_template");

                    b.HasIndex(new[] { "UserId" }, "idx_user_missions_user");

                    b.ToTable("user_missions", null, t =>
                        {
                            t.HasComment("Missions assigned to users with their status");
                        });
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Account", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.Campaign", "Campaign")
                        .WithMany("Accounts")
                        .HasForeignKey("CampaignId")
                        .HasConstraintName("fk_accounts_campaigns");

                    b.HasOne("FinalProject.Infrastructure.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_accounts_users");

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Achievement", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.UserMission", "UserMission")
                        .WithMany("Achievements")
                        .HasForeignKey("UserMissionId")
                        .HasConstraintName("fk_achievements_user_missions");

                    b.Navigation("UserMission");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Campaign", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.User", "User")
                        .WithMany("Campaigns")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_campaigns_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Coupon", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.Campaign", "Campaign")
                        .WithMany("Coupons")
                        .HasForeignKey("CampaignId")
                        .HasConstraintName("fk_coupons_campaigns");

                    b.HasOne("FinalProject.Infrastructure.Supplier", "Supplier")
                        .WithMany("Coupons")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("fk_coupons_suppliers");

                    b.Navigation("Campaign");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Product", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .HasConstraintName("fk_products_types");

                    b.HasOne("FinalProject.Infrastructure.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("fk_products_suppliers");

                    b.Navigation("ProductType");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Sale", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.Account", "Account")
                        .WithMany("Sales")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_sales_accounts");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.SaleDetail", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.Product", "Product")
                        .WithMany("SaleDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_sale_details_products");

                    b.HasOne("FinalProject.Infrastructure.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .HasConstraintName("fk_sale_details_sales");

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Supplier", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.SupplierType", "SupplierType")
                        .WithMany("Suppliers")
                        .HasForeignKey("SupplierTypeId")
                        .HasConstraintName("fk_suppliers_types");

                    b.Navigation("SupplierType");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Transfer", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.Account", "DestinationAccount")
                        .WithMany("TransferDestinationAccounts")
                        .HasForeignKey("DestinationAccountId")
                        .HasConstraintName("fk_transfers_destination");

                    b.HasOne("FinalProject.Infrastructure.Account", "SourceAccount")
                        .WithMany("TransferSourceAccounts")
                        .HasForeignKey("SourceAccountId")
                        .HasConstraintName("fk_transfers_source");

                    b.Navigation("DestinationAccount");

                    b.Navigation("SourceAccount");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.User", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_users_roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.UserMission", b =>
                {
                    b.HasOne("FinalProject.Infrastructure.MissionTemplate", "Mission")
                        .WithMany("UserMissions")
                        .HasForeignKey("MissionId")
                        .HasConstraintName("fk_user_missions_templates");

                    b.HasOne("FinalProject.Infrastructure.Sale", "Sale")
                        .WithMany("UserMissions")
                        .HasForeignKey("SaleId")
                        .HasConstraintName("fk_user_missions_sales");

                    b.HasOne("FinalProject.Infrastructure.User", "User")
                        .WithMany("UserMissions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_missions_users");

                    b.Navigation("Mission");

                    b.Navigation("Sale");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Account", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("TransferDestinationAccounts");

                    b.Navigation("TransferSourceAccounts");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Campaign", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.MissionTemplate", b =>
                {
                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Product", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Sale", b =>
                {
                    b.Navigation("SaleDetails");

                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.Supplier", b =>
                {
                    b.Navigation("Coupons");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.SupplierType", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Campaigns");

                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("FinalProject.Infrastructure.UserMission", b =>
                {
                    b.Navigation("Achievements");
                });
#pragma warning restore 612, 618
        }
    }
}
